<a href="https://colab.research.google.com/github/SundeepChaluvadi/PyTorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Math Operation

*   Add, Subtract, Multiply, Divide, Remianders, Exponents
*   Shorthand and Longhand
*   Reassignment





In [1]:
import torch
import numpy as np

In [2]:
np1 = np.random.rand(2,3)
np1

array([[0.52238337, 0.67154138, 0.53692602],
       [0.61713694, 0.8968046 , 0.89366308]])

In [4]:
tensor_2d = torch.tensor(np1)
tensor_2d

tensor([[0.5224, 0.6715, 0.5369],
        [0.6171, 0.8968, 0.8937]], dtype=torch.float64)

In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

print(tensor_a+tensor_b)

tensor([ 6,  8, 10, 12])


In [6]:
# Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [12]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [14]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [15]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [16]:
# Division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [19]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [20]:
# Exponents
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [27]:
# another way to write longhand
# tensor_a.add(tensor_b)

In [28]:
# Reassignment
tensor_a + tensor_b

tensor([16, 20, 24, 28])

In [36]:
tensor_a = torch.tensor([1,2,3,4])
tensor_a, tensor_b

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]))

In [37]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])