<a href="https://colab.research.google.com/github/SundeepChaluvadi/PyTorch-Tutorial/blob/main/Tensor_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshape and View

In [6]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# Reshape If we dont the know the number of Items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_torch3 = my_torch2.reshape(-1, 5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_torch4 = my_torch4.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
# With Reshape and View, They will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch5[1] = 80085
my_torch5

tensor([    0, 80085,     2,     3,     4,     5,     6,     7,     8,     9])

In [20]:
my_torch6

tensor([[    0, 80085,     2,     3,     4],
        [    5,     6,     7,     8,     9]])

## Slices

In [21]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_torch7[7]

tensor(7)

In [24]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
my_torch8[1]

tensor([2, 3])

In [28]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [30]:
my_torch8[:,0]

tensor([0, 2, 4, 6, 8])

In [31]:
my_torch8[3,:]

tensor([6, 7])

In [32]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])