<a href="https://colab.research.google.com/github/SundeepChaluvadi/PyTorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors


*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type
*   Similar to Numpy arrays, but full of fun things that make them work better on GPU's
*   default data type of Float32
*   More suitable for deep learning than a numpy array





In [2]:
import torch
import numpy as np

# Lists

In [4]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [5]:
my_list2 = [[1,2,3], [4,5,6]]
my_list2

[[1, 2, 3], [4, 5, 6]]

# Numpy Arrays

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.51663583, 0.42813086, 0.41647122, 0.72001964],
       [0.57792527, 0.45322244, 0.54392244, 0.32235206],
       [0.3662019 , 0.72602674, 0.9626993 , 0.53260423]])

In [10]:
np1.dtype

dtype('float64')

# Tensors

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.6846,  0.7801,  0.0863, -0.4609],
        [-0.4748, -0.2576,  0.3678, -1.4458],
        [-2.3787,  0.1160, -0.0168, -0.0848]])

In [13]:
tensor_3d = torch.randn(3,4,4)
tensor_3d

tensor([[[-0.5347, -0.9750, -1.4213,  1.4315],
         [ 0.1708,  0.9721,  1.3290,  0.2924],
         [-0.2995,  0.7788,  0.7739, -0.1396],
         [ 0.8054,  0.3823, -0.7589,  0.6215]],

        [[-0.6940,  0.2436, -1.5789,  0.2307],
         [ 0.7422,  1.0667,  0.2615,  0.7215],
         [ 0.6983, -0.4673,  0.7485,  0.9365],
         [ 0.6964,  0.5286, -1.3740, -0.1006]],

        [[ 0.7231, -0.7836,  0.5015,  0.2386],
         [ 1.1794,  0.3606,  0.5756, -0.0207],
         [-0.2603,  1.0259,  1.2511,  0.8752],
         [-0.4221, -0.1868, -0.0889, -0.0313]]])

In [14]:
tensor_zeros = torch.zeros(2,3,4)
tensor_zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### Create a Tensor out of a Numpy Array

In [16]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5166, 0.4281, 0.4165, 0.7200],
        [0.5779, 0.4532, 0.5439, 0.3224],
        [0.3662, 0.7260, 0.9627, 0.5326]], dtype=torch.float64)

In [17]:
tensor_2d.dtype

torch.float32